site_name: Портфолио Петухова Кирилла
site_description: Портфолио студента программы "Нейротехнологии и программирование"
site_author: Петухов Кирилл

site_url: https://kirill12-source.github.io/python-sem2-lab1/

theme:
  name: material
  palette:
    primary: teal
    accent: deep purple
  font:
    text: Roboto
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - Главная: index.md
  - Об авторе: about.md
  - Лабораторные работы:
    - 1 семестр:
      - Лабораторная №10: semester1/lab10.md
      - Лабораторная №11: semester1/lab11.md
    - 2 семестр:
      - Лабораторная №1: semester2/lab1.md
      - Лабораторная №2: semester2/lab2.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - footnotes
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KirillPetukhov1


copyright: |
  &copy; 2026 Петухов Кирилл. Создано с помощью <a href="https://www.mkdocs.org/" target="_blank">MkDocs</a> и темы <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank">Material</a>.
